service: bio_health_group
image: bio_health_group

servers:
  web:
    - <%= ENV.fetch("DEPLOY_SERVER") %>
  job:
    hosts:
      - <%= ENV.fetch("DEPLOY_SERVER") %>
    cmd: bin/jobs

proxy:
  ssl: true
  host: <%= ENV.fetch("APPLICATION_HOST") %>
  app_port: 3000

registry:
  server: <%= ENV.fetch("REGISTRY_SERVER") %>
  username: <%= ENV.fetch("REGISTRY_USER", "_") %>
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  secret:
    - RAILS_MASTER_KEY
  clear:
    SOLID_QUEUE_IN_PUMA: false
    APPLICATION_HOST: <%= ENV.fetch("APPLICATION_HOST") %>
    APPLICATION_URL: <%= ENV.fetch("APPLICATION_URL") %>
    MAILER_FROM: <%= ENV.fetch("MAILER_FROM", "noreply@biohealthgroup.uy") %>
    CONTACT_EMAIL: <%= ENV.fetch("CONTACT_EMAIL") %>
    SMTP_ADDRESS: <%= ENV.fetch("SMTP_ADDRESS", "smtp.gmail.com") %>
    SMTP_PORT: <%= ENV.fetch("SMTP_PORT", "587") %>
    SMTP_AUTHENTICATION: <%= ENV.fetch("SMTP_AUTHENTICATION", "plain") %>
    RAILS_LOG_LEVEL: info

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole --include-password"

volumes:
  - "bio_health_group_storage:/rails/storage"

asset_path: /rails/public/assets

builder:
  arch: amd64

ssh:
  user: root
